spring:
  application:
    name: booking-state-machine
  output:
    ansi:
      enabled: always
  datasource:
    platform: h2
    url: "jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false"
    username: sa
    password:
  jpa:
    generate-ddl: true
    hibernate:
      use-new-id-generator-mappings: true
  data:
    rest:
      enable-enum-translation: true

logging:
  level:
    root: 'INFO'
    org.hibernate.SQL: DEBUG