spring:
  application:
    name: acceptance-state-machine
  output:
    ansi:
      enabled: always
  datasource:
    platform: POSTGRESQL
    url: "jdbc:postgresql://localhost:5432/acceptance-booking"
    username: postgres
    password: admin

  jpa:
    database: POSTGRESQL
    generate-ddl: true
    hibernate:
      use-new-id-generator-mappings: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  data:
    rest:
      enable-enum-translation: true

logging:
  level:
    root: 'INFO'
    org.hibernate.SQL: DEBUG
    org.springframework.statemachine: DEBUG
